# Generated by Django 2.2.4 on 2019-08-26 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crcapp', '0002_auto_20180731_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name_plural': 'Orders'},
        ),
    ]
